export const routes = {
  home: "/",
  register: "/register",
  login: "/login",
  resetPassword: "/reset-password",
  verify: "/verify",
  updatePassword: "/update-password",
  dashboard: "/dashboard",
  team: "/team",
  investment: "/investment",
  income: "/income",
  assets: "/assets",
  subscription: "/subscription",
  profile: "/profile",
  maintenance: "/maintenance",
  privacy: "/privacy-policy",
  terms: "/terms-conditions",
  userAgreement: "/user-agreement",
  support: "/support",
};
